# Basic

In [1]:
%load_ext autoreload
%autoreload all

In [2]:
import polars as pl
import pickle

import src.graph_tokenizer_gd_tree_dev.config as config
import src.graph_tokenizer_gd_tree_dev.graph_fct as graph_fct

D = config.TokenizerParam.max_dist_candidate

In [8]:
pl.read_parquet(config.BasicConfig.relation_path)["relation"].n_unique()

113

In [3]:
pl.read_parquet(config.BasicConfig.concept_path)

shape: (447_421, 7)
┌──────────────┬──────────────┬──────────────┬──────────────┬─────────────┬────────────┬───────────┐
│ id           ┆ label        ┆ concept_type ┆ sem_tag      ┆ top_categor ┆ collection ┆ is_mapped │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆ y           ┆ ---        ┆ ---       │
│ str          ┆ str          ┆ str          ┆ str          ┆ ---         ┆ list[str]  ┆ bool      │
│              ┆              ┆              ┆              ┆ str         ┆            ┆           │
╞══════════════╪══════════════╪══════════════╪══════════════╪═════════════╪════════════╪═══════════╡
│ 26564000     ┆ Japanese     ┆ SCT_PRE      ┆ organism     ┆ organism    ┆ null       ┆ false     │
│              ┆ giant        ┆              ┆              ┆             ┆            ┆           │
│              ┆ salamander   ┆              ┆              ┆             ┆            ┆           │
│              ┆ (org…        ┆              ┆              ┆             ┆            ┆           │
│ 125401004    ┆ Nuclear      ┆ SCT_PRE      ┆ morphologic  ┆ body        ┆ null       ┆ false     │
│              ┆ membrane pro ┆              ┆ abnormality  ┆ structure   ┆            ┆           │
│              ┆ liferation…  ┆              ┆              ┆             ┆            ┆           │
│ 427118006    ┆ Endoscopic   ┆ SCT_PRE      ┆ procedure    ┆ procedure   ┆ null       ┆ false     │
│              ┆ radiofrequen ┆              ┆              ┆             ┆            ┆           │
│              ┆ cy abla…     ┆              ┆              ┆             ┆            ┆           │
│ 729295002    ┆ Entire       ┆ SCT_PRE      ┆ body         ┆ body        ┆ null       ┆ false     │
│              ┆ anterior     ┆              ┆ structure    ┆ structure   ┆            ┆           │
│              ┆ deep         ┆              ┆              ┆             ┆            ┆           │
│              ┆ temporal …   ┆              ┆              ┆             ┆            ┆           │
│ 705380001    ┆ Housekeeping ┆ SCT_PRE      ┆ physical     ┆ physical    ┆ null       ┆ false     │
│              ┆ assistive    ┆              ┆ object       ┆ object      ┆            ┆           │
│              ┆ device …     ┆              ┆              ┆             ┆            ┆           │
│ …            ┆ …            ┆ …            ┆ …            ┆ …           ┆ …          ┆ …         │
│ 164839006:11 ┆ 164839006|Di ┆ SCT_POST     ┆ procedure    ┆ procedure   ┆ ["labo"]   ┆ true      │
│ 6686009=2584 ┆ rect         ┆              ┆              ┆             ┆            ┆           │
│ 74009,…      ┆ microscopy   ┆              ┆              ┆             ┆            ┆           │
│              ┆ (p…          ┆              ┆              ┆             ┆            ┆           │
│ 726867007    ┆ Entire       ┆ SCT_PRE      ┆ body         ┆ body        ┆ null       ┆ false     │
│              ┆ lamina       ┆              ┆ structure    ┆ structure   ┆            ┆           │
│              ┆ muscularis   ┆              ┆              ┆             ┆            ┆           │
│              ┆ of mu…       ┆              ┆              ┆             ┆            ┆           │
│ 262144001    ┆ Simon        ┆ SCT_PRE      ┆ qualifier    ┆ qualifier   ┆ null       ┆ false     │
│              ┆ (qualifier   ┆              ┆ value        ┆ value       ┆            ┆           │
│              ┆ value)       ┆              ┆              ┆             ┆            ┆           │
│ 777205002    ┆ Product      ┆ SCT_PRE      ┆ medicinal    ┆ product     ┆ null       ┆ false     │
│              ┆ containing   ┆              ┆ product      ┆             ┆            ┆           │
│              ┆ only piogli… ┆              ┆              ┆             ┆            ┆           │
│ 122441001:11 ┆ 122441001|De ┆ SCT_POST     ┆ procedure    ┆ procedure   ┆ ["labo"]   ┆ true      │
│ 6686009=1225 ┆ tection of   ┆              ┆              ┆             ┆            ┆           │
│ 55007,…      ┆ parasit…     ┆              ┆              ┆             ┆            ┆           │
└──────────────┴──────────────┴──────────────┴──────────────┴─────────────┴────────────┴───────────┘

In [10]:
pl.read_parquet(config.BasicConfig.concept_path).filter(pl.col("concept_type") =="SCT_PRE")["id"].n_unique()

420716

In [4]:
graph_fct.build_combined_subgraphs_and_id2label(D)

In [4]:
id_to_label, combined_subgraphs = graph_fct.get_combined_combined_subgraphs_and_id2label()

In [5]:
import networkx as nx
nx.dag_longest_path_length(combined_subgraphs)   # returns the length (number of edges) of the longest path

30

In [14]:
nx.number_weakly_connected_components(combined_subgraphs)
combined_subgraphs.number_of_nodes()
combined_subgraphs.number_of_edges()

293146

In [15]:
pl.read_parquet(config.BasicConfig.relation_path)

shape: (1_684_197, 5)
┌─────────────────────┬─────────────────────┬─────────────────────┬───────────┬────────────────────┐
│ src.id              ┆ src.label           ┆ relation            ┆ dst.id    ┆ dst.label          │
│ ---                 ┆ ---                 ┆ ---                 ┆ ---       ┆ ---                │
│ str                 ┆ str                 ┆ str                 ┆ str       ┆ str                │
╞═════════════════════╪═════════════════════╪═════════════════════╪═══════════╪════════════════════╡
│ 313942007           ┆ Helicobacter pylori ┆ COMPONENT           ┆ 120656006 ┆ Antibody to        │
│                     ┆ immunoglob…         ┆                     ┆           ┆ Helicobacter       │
│                     ┆                     ┆                     ┆           ┆ pylor…             │
│ 254747004           ┆ Aggressive          ┆ FINDING_SITE        ┆ 39937001  ┆ Skin structure     │
│                     ┆ fibromatosis of     ┆                     ┆           ┆ (body structure…   │
│                     ┆ ski…                ┆                     ┆           ┆                    │
│ 10852821000119109   ┆ Traumatic injury of ┆ IS_A                ┆ 446028001 ┆ Traumatic injury   │
│                     ┆ digital ne…         ┆                     ┆           ┆ of digital ne…     │
│ 708167009           ┆ No cutaneous        ┆ FINDING_CONTEXT     ┆ 410516002 ┆ Known absent       │
│                     ┆ papillomatosis (s…  ┆                     ┆           ┆ (qualifier value)  │
│ 219471010000106     ┆ Presence of         ┆ DIRECT_SITE         ┆ 122575003 ┆ Urine specimen     │
│                     ┆ pentetrazol in uri… ┆                     ┆           ┆ (specimen)         │
│ …                   ┆ …                   ┆ …                   ┆ …         ┆ …                  │
│ 117033003:116686009 ┆ 117033003|Aerobic   ┆ COMPONENT           ┆ 43690008  ┆ Genus              │
│ =258574006,…        ┆ microbial cu…       ┆                     ┆           ┆ Lactobacillus      │
│                     ┆                     ┆                     ┆           ┆ (organism)         │
│ 317148009           ┆ Product containing  ┆ HAS_PRECISE_ACTIVE_ ┆ 91023007  ┆ Alverine citrate   │
│                     ┆ precisely a…        ┆ INGREDIENT          ┆           ┆ (substance)        │
│ 275648006           ┆ Refer for medical   ┆ METHOD              ┆ 129276002 ┆ Referral - action  │
│                     ┆ physics (pro…       ┆                     ┆           ┆ (qualifier v…      │
│ 24727006            ┆ Temperature         ┆ IS_A                ┆ 386053000 ┆ Evaluation         │
│                     ┆ gradient studies (… ┆                     ┆           ┆ procedure          │
│                     ┆                     ┆                     ┆           ┆ (procedur…         │
│ 321691000119106     ┆ Arthritis of left   ┆ PATHOLOGICAL_PROCES ┆ 441862004 ┆ Infectious process │
│                     ┆ knee caused …       ┆ S                   ┆           ┆ (qualifier …       │
└─────────────────────┴─────────────────────┴─────────────────────┴───────────┴────────────────────┘